package com.example.brightbuds_app.services;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.util.Log;

import com.example.brightbuds_app.models.Progress;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Generates structured PDF reports for both admin and parent users and can automatically open the email client with the report attached.
 * Uses iText for PDF generation.
 */
public class PDFReportService {

    private static final String TAG = "PDFReportService";
    private final Context context;
    private long startTimestamp = 0;
    private long endTimestamp = 0;

    public interface PDFCallback {
        void onSuccess(String filePath);
        void onFailure(Exception e);
    }

    public PDFReportService(Context context) {
        this.context = context;
    }

    /** Optional: set date range filter for report content */
    public void setDateRange(long startTimestamp, long endTimestamp) {
        this.startTimestamp = startTimestamp;
        this.endTimestamp = endTimestamp;
    }

    // ADMIN REPORT (SYSTEM-WIDE)
    public void generateAdminProgressReport(List<Progress> progressList,
                                            double avgScore,
                                            int totalPlays,
                                            String generatedBy,
                                            Map<String, String> childNames,
                                            Map<String, String> parentNames,
                                            PDFCallback callback) {
        Log.d(TAG, "📊 Generating ADMIN report by: " + generatedBy);

        File file = createReportFile("BrightBuds_Admin_Report");
        if (file == null) {
            callback.onFailure(new IOException("Unable to create report file"));
            return;
        }

        try (FileOutputStream outputStream = new FileOutputStream(file)) {
            Document document = new Document();
            PdfWriter.getInstance(document, outputStream);
            document.open();

            // Header Fonts
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, BaseColor.BLACK);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.BLACK);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLACK);
            Font boldFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.BLACK);
            Font smallFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.DARK_GRAY);

            // Report Header
            Paragraph title = new Paragraph("BrightBuds System Progress Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(15);
            document.add(title);

            SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault());
            document.add(new Paragraph("Generated by: " + generatedBy, normalFont));
            document.add(new Paragraph("Generated on: " + sdf.format(new Date()), normalFont));
            document.add(new Paragraph(" "));

            // Overview Section
            document.add(new Paragraph("System Overview", headerFont));
            document.add(new Paragraph(" "));

            int totalParents = 0;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
                totalParents = new HashSet<>(progressList.stream().map(Progress::getParentId).filter(Objects::nonNull).toList()).size();
            }
            int totalChildren = 0;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
                totalChildren = new HashSet<>(progressList.stream().map(Progress::getChildId).filter(Objects::nonNull).toList()).size();
            }
            int totalModules = progressList.size();
            int completedModules = (int) progressList.stream().filter(p -> "completed".equalsIgnoreCase(p.getStatus())).count();
            double completionRate = totalModules > 0 ? (completedModules * 100.0 / totalModules) : 0;

            PdfPTable overviewTable = new PdfPTable(2);
            overviewTable.setWidthPercentage(100);
            addTableHeader(overviewTable, new String[]{"Metric", "Value"});

            addOverviewRow(overviewTable, "Total Parents", String.valueOf(totalParents), normalFont);
            addOverviewRow(overviewTable, "Total Children", String.valueOf(totalChildren), normalFont);
            addOverviewRow(overviewTable, "Total Modules Played", String.valueOf(totalPlays), normalFont);
            addOverviewRow(overviewTable, "Modules Completed", String.valueOf(completedModules), normalFont);
            addOverviewRow(overviewTable, "Average Score", String.format(Locale.getDefault(), "%.1f%%", avgScore), normalFont);
            addOverviewRow(overviewTable, "Completion Rate", String.format(Locale.getDefault(), "%.1f%%", completionRate), normalFont);
            document.add(overviewTable);

            // Detailed Progress by Child Section
            document.add(new Paragraph("\nDetailed Progress by Child", headerFont));
            document.add(new Paragraph(" "));

            PdfPTable detailedTable = new PdfPTable(4);
            detailedTable.setWidthPercentage(100);
            addTableHeader(detailedTable, new String[]{"Child", "Parent", "Module Count", "Average Score"});

            // Group progress by child
            Map<String, List<Progress>> progressByChild = new HashMap<>();
            for (Progress progress : progressList) {
                String childId = progress.getChildId();
                if (!progressByChild.containsKey(childId)) {
                    progressByChild.put(childId, new ArrayList<>());
                }
                progressByChild.get(childId).add(progress);
            }

            // Add rows for each child
            for (Map.Entry<String, List<Progress>> entry : progressByChild.entrySet()) {
                String childId = entry.getKey();
                List<Progress> childProgress = entry.getValue();

                String childName = childNames.getOrDefault(childId, "Unknown Child");
                String parentName = parentNames.getOrDefault(childProgress.get(0).getParentId(), "Unknown Parent");
                int moduleCount = childProgress.size();
                double childAvgScore = childProgress.stream().mapToDouble(Progress::getScore).average().orElse(0);

                addDetailedRow(detailedTable,
                        childName,
                        parentName,
                        String.valueOf(moduleCount),
                        String.format(Locale.getDefault(), "%.1f%%", childAvgScore),
                        BaseColor.WHITE,
                        normalFont);
            }

            document.add(detailedTable);

            // Footer
            document.add(new Paragraph("\nGenerated automatically by BrightBuds App", smallFont));
            document.add(new Paragraph("© 2025 BrightBuds Learning Platform", smallFont));

            document.close();
            Log.i(TAG, "✅ Admin report generated: " + file.getAbsolutePath());
            callback.onSuccess(file.getAbsolutePath());

        } catch (Exception e) {
            Log.e(TAG, "❌ Admin PDF generation failed", e);
            callback.onFailure(e);
        }
    }

    // PARENT REPORT (FAMILY-LEVEL)
    public void generateProgressReport(List<Progress> progressList,
                                       double avgScore,
                                       int totalPlays,
                                       String parentName,
                                       Map<String, String> childNames,
                                       PDFCallback callback) {
        Log.d(TAG, "📊 Generating parent report for " + parentName);

        File file = createReportFile("BrightBuds_Family_Report");
        if (file == null) {
            callback.onFailure(new IOException("Unable to create report file"));
            return;
        }

        try (FileOutputStream outputStream = new FileOutputStream(file)) {
            Document document = new Document();
            PdfWriter.getInstance(document, outputStream);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, BaseColor.BLACK);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.BLACK);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLACK);
            Font boldFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.BLACK);
            Font smallFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.DARK_GRAY);

            Paragraph title = new Paragraph("BrightBuds Learning Progress Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(15);
            document.add(title);

            SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault());
            document.add(new Paragraph("Parent: " + parentName, normalFont));
            document.add(new Paragraph("Generated on: " + sdf.format(new Date()), normalFont));

            // Family Summary - Average Plays/Score
            document.add(new Paragraph("Family Summary - Average Plays/Score: " + totalPlays + " plays, " +
                    String.format(Locale.getDefault(), "%.1f%%", avgScore) + " average score", boldFont));
            document.add(new Paragraph(" "));

            // Family Summary Table
            document.add(new Paragraph("Family Summary", headerFont));
            PdfPTable summaryTable = new PdfPTable(3);
            summaryTable.setWidthPercentage(100);
            addTableHeader(summaryTable, new String[]{"Child", "Modules Played", "Average Score"});

            for (String childId : childNames.keySet()) {
                List<Progress> childProgress = progressList.stream()
                        .filter(p -> p.getChildId() != null && p.getChildId().equals(childId))
                        .collect(Collectors.toList());

                int modulesPlayed = childProgress.size();
                double avg = childProgress.stream()
                        .mapToDouble(Progress::getScore).average().orElse(0);

                addSummaryRow(summaryTable,
                        childNames.get(childId),
                        String.valueOf(modulesPlayed),
                        String.format(Locale.getDefault(), "%.1f%%", avg),
                        BaseColor.WHITE,
                        normalFont);
            }

            document.add(summaryTable);

            // Detailed Progress Section
            document.add(new Paragraph("\nDetailed Progress", headerFont));
            document.add(new Paragraph(" "));

            PdfPTable detailedTable = new PdfPTable(4);
            detailedTable.setWidthPercentage(100);
            addTableHeader(detailedTable, new String[]{"Child", "Module", "Module Count", "Score"});

            // Group by child and module to show detailed counts
            Map<String, Map<String, List<Progress>>> progressByChildAndModule = new HashMap<>();
            for (Progress progress : progressList) {
                String childId = progress.getChildId();
                String moduleName = progress.getModuleName() != null ? progress.getModuleName() : "Unknown Module";

                if (!progressByChildAndModule.containsKey(childId)) {
                    progressByChildAndModule.put(childId, new HashMap<>());
                }
                if (!progressByChildAndModule.get(childId).containsKey(moduleName)) {
                    progressByChildAndModule.get(childId).put(moduleName, new ArrayList<>());
                }
                progressByChildAndModule.get(childId).get(moduleName).add(progress);
            }

            // Add detailed rows
            for (Map.Entry<String, Map<String, List<Progress>>> childEntry : progressByChildAndModule.entrySet()) {
                String childId = childEntry.getKey();
                String childName = childNames.getOrDefault(childId, "Unknown Child");

                for (Map.Entry<String, List<Progress>> moduleEntry : childEntry.getValue().entrySet()) {
                    String moduleName = moduleEntry.getKey();
                    List<Progress> moduleProgress = moduleEntry.getValue();
                    int moduleCount = moduleProgress.size();
                    double moduleAvgScore = moduleProgress.stream().mapToDouble(Progress::getScore).average().orElse(0);

                    addDetailedRow(detailedTable,
                            childName,
                            moduleName,
                            String.valueOf(moduleCount),
                            String.format(Locale.getDefault(), "%.1f%%", moduleAvgScore),
                            BaseColor.WHITE,
                            normalFont);
                }
            }

            document.add(detailedTable);
            document.add(new Paragraph("\nGenerated automatically by BrightBuds App", smallFont));
            document.add(new Paragraph("© 2025 BrightBuds Learning Platform", smallFont));

            document.close();

            // Email the report automatically
            sendReportViaEmail(file, parentName);

            callback.onSuccess(file.getAbsolutePath());
        } catch (Exception e) {
            Log.e(TAG, "❌ Parent PDF generation failed", e);
            callback.onFailure(e);
        }
    }

    // UTILITIES
    /** Create report directory and file name dynamically */
    private File createReportFile(String prefix) {
        String fileName = prefix + "_" + new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(new Date()) + ".pdf";
        File reportsDir;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            reportsDir = new File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "BrightBudsReports");
        } else {
            reportsDir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS), "BrightBudsReports");
        }
        if (!reportsDir.exists() && !reportsDir.mkdirs()) {
            Log.e(TAG, "❌ Failed to create directory: " + reportsDir);
            return null;
        }
        return new File(reportsDir, fileName);
    }

    /** Add a metric row for summary tables */
    private void addOverviewRow(PdfPTable table, String metric, String value, Font font) {
        PdfPCell c1 = new PdfPCell(new Phrase(metric, font));
        PdfPCell c2 = new PdfPCell(new Phrase(value, font));
        c1.setPadding(6);
        c2.setPadding(6);
        c1.setHorizontalAlignment(Element.ALIGN_LEFT);
        c2.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.addCell(c2);
    }

    /** Add child-level summary data row */
    private void addSummaryRow(PdfPTable table, String name, String modules, String avg, BaseColor bg, Font font) {
        PdfPCell[] cells = {
                new PdfPCell(new Phrase(name, font)),
                new PdfPCell(new Phrase(modules, font)),
                new PdfPCell(new Phrase(avg, font))
        };
        for (PdfPCell c : cells) {
            c.setBackgroundColor(bg);
            c.setPadding(6);
            c.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c);
        }
    }

    /** Add detailed row with 4 columns */
    private void addDetailedRow(PdfPTable table, String child, String module, String count, String score,
                                BaseColor bg, Font font) {
        PdfPCell[] cells = {
                new PdfPCell(new Phrase(child, font)),
                new PdfPCell(new Phrase(module, font)),
                new PdfPCell(new Phrase(count, font)),
                new PdfPCell(new Phrase(score, font))
        };
        for (PdfPCell c : cells) {
            c.setBackgroundColor(bg);
            c.setPadding(6);
            c.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c);
        }
    }

    /** Add table headers with style */
    private void addTableHeader(PdfPTable table, String[] headers) {
        BaseColor headerColor = new BaseColor(70, 130, 180);
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.WHITE);
        for (String h : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(h, headerFont));
            cell.setBackgroundColor(headerColor);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setPadding(7);
            table.addCell(cell);
        }
    }

    /** Open email intent with the PDF attached */
    private void sendReportViaEmail(File file, String parentName) {
        try {
            Intent emailIntent = new Intent(Intent.ACTION_SEND);
            emailIntent.setType("application/pdf");
            emailIntent.putExtra(Intent.EXTRA_SUBJECT, "BrightBuds Progress Report");
            emailIntent.putExtra(Intent.EXTRA_TEXT, "Hello " + parentName + ",\n\nPlease find attached your child's BrightBuds learning progress report.\n\nKind regards,\nBrightBuds Team");
            emailIntent.putExtra(Intent.EXTRA_STREAM, Uri.fromFile(file));
            emailIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(Intent.createChooser(emailIntent, "Send Report via Email"));
        } catch (Exception e) {
            Log.e(TAG, "⚠️ Failed to open email client", e);
        }
    }
}